apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: guy-app
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: ClusterIP
